In [1]:
#Batching 

In [ ]:
import tensorflow as tf
import pathlib
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [14]:
first = tf.data.Dataset.range(50)
second = tf.data.Dataset.range(50,100)
dataset = tf.data.Dataset.zip((first,second))
batched_dataset = dataset.batch(3)

for i in batched_dataset.take(4):
  print([j.numpy() for j in i])

[array([0, 1, 2]), array([50, 51, 52])]
[array([3, 4, 5]), array([53, 54, 55])]
[array([6, 7, 8]), array([56, 57, 58])]
[array([ 9, 10, 11]), array([59, 60, 61])]


In [15]:
batched_dataset

<BatchDataset shapes: ((None,), (None,)), types: (tf.int64, tf.int64)>

In [16]:
len(batched_dataset)

17

In [17]:
#removing the last batch if it is of improper shape that is if dimensions of last batch are not equal to the defined ones

In [18]:
batched_dataset = dataset.batch(3, drop_remainder=True)
batched_dataset

<BatchDataset shapes: ((3,), (3,)), types: (tf.int64, tf.int64)>

In [19]:
len(batched_dataset)

16

In [20]:
for i in batched_dataset.take(4):
  print([j.numpy() for j in i])

[array([0, 1, 2]), array([50, 51, 52])]
[array([3, 4, 5]), array([53, 54, 55])]
[array([6, 7, 8]), array([56, 57, 58])]
[array([ 9, 10, 11]), array([59, 60, 61])]


In [ ]:
# batched tensors with padding
# suitable for models working on sequential data
# for e.g. in speech related models input is of different dimensions

In [31]:
A = (tf.data.Dataset.range(1, 10, output_type=tf.int32).map(lambda x: tf.fill([x], x)))
B = A.padded_batch(4)
for element in B.as_numpy_iterator():
  print(element)

[[1 0 0 0]
 [2 2 0 0]
 [3 3 3 0]
 [4 4 4 4]]
[[5 5 5 5 5 0 0 0]
 [6 6 6 6 6 6 0 0]
 [7 7 7 7 7 7 7 0]
 [8 8 8 8 8 8 8 8]]
[[9 9 9 9 9 9 9 9 9]]
