In [1]:
import tensorflow as tf
import pathlib
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


In [2]:
dataset = tf.data.Dataset.from_tensor_slices([3,4,5,6])
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [3]:
for elem in dataset:
  print(elem.numpy())

3
4
5
6


In [4]:
dataset=dataset.reduce(10, lambda state, value: state + value)
dataset

<tf.Tensor: shape=(), dtype=int32, numpy=28>

In [5]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10],maxval=5,dtype=tf.int32))

print(dataset1)

<TensorSliceDataset shapes: (10,), types: tf.int32>


In [6]:
for z in dataset1:
  print(z.numpy())

[1 4 1 4 4 2 1 4 2 3]
[0 4 2 2 3 2 1 1 4 4]
[3 1 2 4 3 4 1 2 4 1]
[2 2 3 3 2 1 3 0 2 4]


In [7]:
dataset2 = tf.data.Dataset.from_tensor_slices(
   (tf.random.uniform([4],maxval=4,dtype=tf.int32),
    tf.random.uniform([4, 10], maxval=100, dtype=tf.int32)))

dataset2

<TensorSliceDataset shapes: ((), (10,)), types: (tf.int32, tf.int32)>

In [8]:
for z in dataset2:
  print(z)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([65, 72, 21, 98, 43,  5,  2, 93, 88, 40], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([99, 65, 63, 59, 37,  4, 99, 80, 63, 20], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 6, 47, 39, 88, 84, 42, 59, 34, 78, 87], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([18, 52, 94, 68, 43, 65, 23, 66, 95, 65], dtype=int32)>)


In [9]:
dataset3=tf.data.Dataset.zip((dataset1,dataset2))

In [10]:
dataset3.element_spec

(TensorSpec(shape=(10,), dtype=tf.int32, name=None),
 (TensorSpec(shape=(), dtype=tf.int32, name=None),
  TensorSpec(shape=(10,), dtype=tf.int32, name=None)))

In [11]:
for z in dataset3:
  print(z)

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 4, 1, 4, 4, 2, 1, 4, 2, 3], dtype=int32)>, (<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([65, 72, 21, 98, 43,  5,  2, 93, 88, 40], dtype=int32)>))
(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 4, 2, 2, 3, 2, 1, 1, 4, 4], dtype=int32)>, (<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([99, 65, 63, 59, 37,  4, 99, 80, 63, 20], dtype=int32)>))
(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([3, 1, 2, 4, 3, 4, 1, 2, 4, 1], dtype=int32)>, (<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 6, 47, 39, 88, 84, 42, 59, 34, 78, 87], dtype=int32)>))
(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([2, 2, 3, 3, 2, 1, 3, 0, 2, 4], dtype=int32)>, (<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([18, 52, 94, 68, 43, 65, 23, 66, 95, 65], dtype=in

In [12]:
#Sparse tensor:Tensor having all values 0 except the defined ones

In [13]:
dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4]))

dataset4.element_spec

SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [14]:
for z in dataset4:
  print(z)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [15]:
DATA_URL = 'https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz'

path = tf.keras.utils.get_file('mnist.npz', DATA_URL)
print(path)
with np.load(path) as data:
  train_examples = data['x_train']
  train_labels = data['y_train']
  test_examples = data['x_test']
  test_labels = data['y_test']

11493376/11490434 [==============================] - 0s 0us/step
/root/.keras/datasets/mnist.npz


In [16]:
train_dataset = tf.data.Dataset.from_tensor_slices((train_examples, train_labels))
test_dataset = tf.data.Dataset.from_tensor_slices((test_examples, test_labels))

In [17]:
BATCH_SIZE = 64
SHUFFLE_BUFFER_SIZE = 100

train_dataset = train_dataset.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE)
test_dataset = test_dataset.batch(BATCH_SIZE)

In [18]:
tf.random.uniform([4])

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.2220447 , 0.40319335, 0.15863192, 0.5274366 ], dtype=float32)>

In [19]:
print(tf.SparseTensor(indices=[[1, 0], [2, 2]], values=[4, 6], dense_shape=[10, 4]))

SparseTensor(indices=tf.Tensor(
[[1 0]
 [2 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([4 6], shape=(2,), dtype=int32), dense_shape=tf.Tensor([10  4], shape=(2,), dtype=int64))


In [20]:
train, test = tf.keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [21]:
images, labels = train
images = images/255

dataset = tf.data.Dataset.from_tensor_slices((images, labels))
dataset

<TensorSliceDataset shapes: ((28, 28), ()), types: (tf.float64, tf.uint8)>

In [29]:
for z in dataset.take(1):
  print(z)

(<tf.Tensor: shape=(28, 28), dtype=float64, numpy=
array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ,

In [ ]:
# download data

In [24]:
flowers = tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True)


228818944/228813984 [==============================] - 2s 0us/step


In [25]:
img_gen = tf.keras.preprocessing.image.ImageDataGenerator(rescale=1./255, rotation_range=20)

In [27]:
images, labels = next(img_gen.flow_from_directory(flowers))

Found 3670 images belonging to 5 classes.


In [28]:
print(images.dtype, images.shape)
print(labels.dtype, labels.shape)

float32 (32, 256, 256, 3)
float32 (32, 5)
